(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
ClearAll["Global`*"];SetDirectory[NotebookDirectory[]];Get["./DefinitionsAndAssumptionsBivariate.m"];
ClearVars;


(* ::Input::Initialization:: *)
ClearVars;\[ScriptR]2Check = rfree+\[Phi];\[CapitalSigma]=0.2;rfree=0.02;\[Phi]=0.08;\[ScriptR]1Check=rfree;
(* First, show that the approximation of the (true) arithmetic return by the Campbell-Viceira approximation
   is good (or at least much better than the geometric approximation)*)
Off[NIntegrate::inumr]; (*Turn off some annoying warning messages*)
ExactMinusApproxLogExpectedPortfolioReturn = 
Plot[{\[DoubleStruckCapitalE]\[GothicR]CheckNInt[\[Stigma],\[CapitalSigma]]-\[DoubleStruckCapitalE]\[GothicR]CheckCVApprox[\[Stigma],\[CapitalSigma]](*,\[DoubleStruckCapitalE]\[GothicR]CheckNInt[\[Stigma],\[CapitalSigma]]-\[DoubleStruckCapitalE]\[GothicR]CheckGeometric[\[Stigma],\[CapitalSigma]]*)}
  ,{\[Stigma],0,1}
  ,AxesLabel->{"\[Stigma]","\[DoubleStruckCapitalE]\[GothicR]-\!\(\*OverscriptBox[\(\[DoubleStruckCapitalE]\[GothicR]\), \(^\)]\)"}
  ,BaseStyle->{FontSize->14}
  ,PlotLabel->"For r = "<>ToString[rfree]<>", \[Phi] = "<>ToString[\[Phi]]<>", \[CapitalSigma] = "<>ToString[\[CapitalSigma]]
  ,PlotStyle->{Black,Red}
,PlotLegend->{"Campbell-Viceira"(*,"Geometric"*)}
,LegendSize->0.75
,LegendTextSpace->5
,LegendPosition->{0.,0.}
]
(*
Export["./Figures/ExactMinusApproxLogExpectedPortfolioReturn.pdf",ExactMinusApproxLogExpectedPortfolioReturn];
Export["./Figures/ExactMinusApproxLogExpectedPortfolioReturn.png",ExactMinusApproxLogExpectedPortfolioReturn,ImageSize\[Rule]72 9];
Export["./Figures/ExactMinusApproxLogExpectedPortfolioReturn.svg",ExactMinusApproxLogExpectedPortfolioReturn];
Print[ExactMinusApproxLogExpectedPortfolioReturn];
On[NIntegrate::inumr];
*)



(* ::Input::Initialization:: *)
\[ScriptR]2Check=0.05;rfree=0.02;\[Phi]=\[ScriptR]2Check-rfree;\[CapitalSigma]=0.2;
ShareVsCRRA = Plot[\[Stigma]2OptApprox[\[CapitalSigma],\[Rho]],{\[Rho],1,5}
,AxesLabel->{"\[Rho]","\[Stigma]2"}
,PlotLabel->"For Parameters r = "<>ToString[rfree]<>", \[Phi] = "<>ToString[\[Phi]]<>", \[CapitalSigma] = "<>ToString[\[CapitalSigma]]
,BaseStyle->{FontSize->14}
];
Export["./Figures/ShareVsCRRA.pdf",ShareVsCRRA];
Export["./Figures/ShareVsCRRA.png",ShareVsCRRA,ImageSize->72 9];
Export["./Figures/ShareVsCRRA.svg",ShareVsCRRA];
Print[ShareVsCRRA];


(* ::Input::Initialization:: *)
Off[NIntegrate::inumr]; (*Turn off some annoying warning messages*)
ShareApproxErr=Plot[{\[Stigma]2OptExact[\[CapitalSigma],\[Rho]]-\[Stigma]2OptApprox[\[CapitalSigma],\[Rho]]},{\[Rho],1.01,5}
,PlotLabel->"For Parameters \[Phi] = "<>ToString[\[Phi]]<>", r = "<>ToString[rfree]<>", \[CapitalSigma] = "<>ToString[\[CapitalSigma]]
,BaseStyle->{FontSize->14}
,AxesLabel->{"\[Rho]","Error"}];
Export["./Figures/ShareApproxErr.pdf",ShareApproxErr];
Export["./Figures/ShareApproxErr.png",ShareApproxErr,ImageSize->72 9];
Export["./Figures/ShareApproxErr.svg",ShareApproxErr];
Print[ShareApproxErr];
On[NIntegrate::inumr];


(* ::Input::Initialization:: *)
Print[Plot[\[DoubleStruckCapitalE]\[GothicCapitalR]GivenOpt\[Stigma]2Approx[\[CapitalSigma]Plot,\[Rho]=2],{\[CapitalSigma]Plot,0.1,0.3}]];


(* ::Input::Initialization:: *)

\[CapitalSigma]\[GothicR]Given\[CapitalSigma]Approx[\[CapitalSigma]_,\[Rho]_] := Block[{\[Stigma]2Approx},
  \[Stigma]2Approx=\[Stigma]2OptApprox[\[CapitalSigma],\[Rho]];
  NIntegrate[PDF[LogNormalDistribution[\[Phi]-(\[CapitalSigma]^2)/2,\[CapitalSigma]],\[CapitalPhi]tp1](\[Stigma]2Approx Log[\[CapitalPhi]tp1]+\[Stigma]2Approx(1-\[Stigma]2Approx)(\[CapitalSigma]^2)/2),{\[CapitalPhi]tp1,0,\[Infinity]}]
];



(* ::Input::Initialization:: *)

Print[Plot[\[CapitalSigma]\[GothicR]Given\[CapitalSigma]Approx[\[CapitalSigma]Plot,3],{\[CapitalSigma]Plot,0.2,0.4}]];
