(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(* Calculate Subscript[\[DoubleStruckCapitalE], t][Exp[(1-\[Rho]) \[Stigma] \[Phi]tp1]; part of formula for expected utility \eqref{eq:exputil} in handout *)
\[DoubleStruckCapitalE]t\[CapitalPhi]tp1Part = Integrate[Exp[(1-\[Rho])\[Stigma] Log[\[CapitalPhi]tp1]] PDF[LogNormalDistribution[\[CurlyPhi]-\[Sigma]^2/2,\[Sigma]],\[CapitalPhi]tp1],{\[CapitalPhi]tp1,0,\[Infinity]}];


(* ::Input::Initialization:: *)
Expectation[Exp[(1-\[Rho])\[Stigma] Log[\[CapitalPhi]tp1]], \[CapitalPhi]tp1\[Distributed]LogNormalDistribution[\[CurlyPhi]-\[Sigma]^2/2,\[Sigma]]];


(* ::Input::Initialization:: *)
log\[DoubleStruckCapitalE]t\[CapitalPhi]tp1Part = Simplify[Log[\[DoubleStruckCapitalE]t\[CapitalPhi]tp1Part]];


(* ::Input::Initialization:: *)
(* Simplify the expression further *)
Simpler4Sub = (1-\[Rho])(\[CurlyPhi] \[Stigma] -\[Stigma](1-(1-\[Rho])\[Stigma])(\[Sigma]^2/2));
Simpler5Sub = (1-\[Rho])(\[CurlyPhi] \[Stigma] -\[Stigma](1-\[Stigma])(\[Sigma]^2/2)-\[Rho] \[Stigma]^2 (\[Sigma]^2/2));
Simpler6Sub = -(\[Rho]-1)(\[CurlyPhi] \[Stigma] -\[Stigma](1-\[Stigma])(\[Sigma]^2/2)-\[Rho] \[Stigma]^2 (\[Sigma]^2/2));


(* ::Input::Initialization:: *)
(* Verify that the simplification is correct *)
Simplify[log\[DoubleStruckCapitalE]t\[CapitalPhi]tp1Part == Simpler6Sub];


(* ::Input::Initialization:: *)
(* Using this result, now compute expected utility; see handout for underlying formula *)
\[DoubleStruckCapitalE]utp1 = Exp[(1-\[Rho])\[Stigma](1-\[Stigma])\[Sigma]^2/2] Exp[log\[DoubleStruckCapitalE]t\[CapitalPhi]tp1Part];


(* ::Input::Initialization:: *)
log\[DoubleStruckCapitalE]utp1 = \[DoubleStruckCapitalE]utp1[[2]]; (* Extracts the exponent on \[ExponentialE]; for some reason, directly taking the Log does not obtain the exponent *)


(* ::Input::Initialization:: *)
(* Verify that a simpler expression (derived in the handout) is correct *)
Simplify[log\[DoubleStruckCapitalE]utp1 == -(\[Rho]-1) (\[CurlyPhi] \[Stigma] - \[Stigma]^2 \[Rho] (\[Sigma]^2/2))]];


(* ::Input::Initialization:: *)
(* Calculate the approximation to the optimal portfolio share *)
Assuming[{\[Stigma]>0,\[Rho]>0,\[CurlyPhi]>0},Maximize[{\[CurlyPhi] \[Stigma] - \[Stigma]^2 \[Rho] (\[Sigma]^2/2),\[CurlyPhi]>0,\[Sigma]>0,\[Rho]>0},\[Stigma]]][[2]];
